name: pohodnik-backend
env: production
buildCommand: npm install
startCommand: npm start
healthCheckPath: /api/health
autoDeploy: true
plan: free
region: frankfurt
envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "10000"
  - key: SUPABASE_URL
    value: https://zxnqwwalthixvyjttdqs.supabase.co
  - key: DB_HOST
    value: db.zxnqwwalthixvyjttdqs.supabase.co
  - key: DB_PORT
    value: "5432"
  - key: DB_USER
    value: postgres
            { 'key': 'DB_PORT', 'value': '5432' },
            { 'key': 'DB_USER', 'sync': false },
            { 'key': 'DB_PASSWORD', 'sync': false },
            { 'key': 'DB_NAME', 'value': 'postgres' },
            { 'key': 'JWT_SECRET', 'generateValue': true },
            {
                'key': 'FRONTEND_URL',
                'value': 'https://your-vercel-app.vercel.app',
            },
        ],
}
